listenAddr = "127.0.0.1:8080"
domain = "127.0.0.1"
[database]
    [database.mysql]
    enable = true
    username = "blog"
    password = "admin"
    ip = "127.0.0.1"
    port = "3306"
    dbname = "Blog"